
language: objective-c
matrix:
  include:
    - osx_image: xcode7.2
    - osx_image: xcode7.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - pod lib lint
  - set -o pipefail
  - xcodebuild test -workspace ESNotification.xcworkspace -scheme ESNotification_OSX -configuration Debug | xcpretty -c
  - xcodebuild test -workspace ESNotification.xcworkspace -scheme ESNotification_iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
notifications:
  email: false
  
